In [1]:
import soccerdata as sd
import pandas as pd

understat = sd.Understat(
            leagues="ESP-La Liga",
            seasons="2425"
        )

df = understat.read_player_season_stats().reset_index()

[03/13/26 08:53:03] INFO     No custom team name replacements found. You can configure these in       ]8;id=351206;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=207731;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\soccerdata\_config.py#92\92]8;;\
                             C:\Users\User\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=328586;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=752923;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\soccerdata\_config.py#198\198]8;;\
                             C:\Users\User\soccerdata\config\league_dict.json.

                    INFO     Saving cached data to C:\Users\User\soccerdata\data\Understat           ]8;id=314293;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=204090;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\soccerdata\_common.py#249\249]8;;\

[2026-03-13 08:53:03] INFO     TLSLibrary:_load_library:397 - Successfully loaded TLS library: C:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\tls_requests\bin\tls-client-xgo-1.13.1-windows-amd64.dll

                    INFO     Successfully loaded TLS library:                                      ]8;id=58047;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\tls_requests\models\libraries.py\libraries.py]8;;\:]8;id=145225;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\tls_requests\models\libraries.py#397\397]8;;\
                             C:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages
                             \tls_requests\bin\tls-client-xgo-1.13.1-windows-amd64.dll

In [3]:
df[df["team"]=="Barcelona"]

,league,season,team,player,league_id,season_id,team_id,player_id,position,matches,...,np_goals,np_xg,assists,xa,shots,key_passes,yellow_cards,red_cards,xg_chain,xg_buildup
84,ESP-La Liga,2425,Barcelona,Andreas Christensen,4,2024,148,200,D S,5,...,0,0.033216,0,0.04022,1,1,3,0,1.476646,1.476646
85,ESP-La Liga,2425,Barcelona,Anssumane Fati,4,2024,148,7967,M S,6,...,0,1.101842,0,0.12386,12,4,1,0,1.886312,0.809995
86,ESP-La Liga,2425,Barcelona,Dani Olmo,4,2024,148,8292,M S,25,...,8,5.151578,4,3.851693,42,27,1,0,17.126844,9.9389
87,ESP-La Liga,2425,Barcelona,Daniel Rodríguez,4,2024,148,11634,M,1,...,0,0.04132,0,0.0,2,0,0,0,0.30606,0.26474
88,ESP-La Liga,2425,Barcelona,Eric Garcia,4,2024,148,8045,D M S,29,...,2,2.354891,3,1.012535,14,7,4,0,12.874616,12.290382
89,ESP-La Liga,2425,Barcelona,Fermín López,4,2024,148,11822,M S,28,...,6,4.756552,5,4.712301,41,29,4,1,15.650715,7.853521
90,ESP-La Liga,2425,Barcelona,Ferrán Torres,4,2024,148,6441,F M S,27,...,10,9.682403,6,3.556156,48,19,1,1,14.05879,2.258016
91,ESP-La Liga,2425,Barcelona,Frenkie de Jong,4,2024,148,7781,M S,26,...,2,1.02432,2,2.302895,5,21,3,0,11.636853,8.71532
92,ESP-La Liga,2425,Barcelona,Gavi,4,2024,148,9804,F M S,26,...,1,1.060117,1,1.652763,11,14,4,0,7.769327,5.841561
93,ESP-La Liga,2425,Barcelona,Gerard Martín,4,2024,148,12821,D S,28,...,1,0.643622,3,1.295845,7,12,2,0,7.371044,6.11158
94,ESP-La Liga,2425,Barcelona,Hector Fort,4,2024,148,12171,D S,17,...,0,0.269494,0,1.301748,6,9,2,0,4.381688,3.519321
95,ESP-La Liga,2425,Barcelona,Iñaki Peña,4,2024,148,7287,GK S,16,...,0,0.0,0,0.0,0,0,1,0,3.90612,3.90612
96,ESP-La Liga,2425,Barcelona,Iñigo Martínez,4,2024,148,2484,D,28,...,0,0.513606,4,2.247953,13,16,5,0,20.049223,19.112831
97,ESP-La Liga,2425,Barcelona,Jules Koundé,4,2024,148,6433,D S,32,...,2,2.743822,3,4.13401,18,32,4,0,24.096324,20.274256
98,ESP-La Liga,2425,Barcelona,Lamine Yamal,4,2024,148,11527,F M S,35,...,9,11.593034,13,14.466478,144,64,3,0,38.307875,18.003249
99,ESP-La Liga,2425,Barcelona,Marc Bernal,4,2024,148,12820,M,3,...,0,0.056063,0,0.011037,2,1,2,0,1.513912,1.446811
100,ESP-La Liga,2425,Barcelona,Marc Casadó,4,2024,148,11151,M S,23,...,1,0.911937,3,1.634876,14,9,2,1,14.53799,13.508166
101,ESP-La Liga,2425,Barcelona,Marc-André ter Stegen,4,2024,148,2090,GK,8,...,0,0.0,0,0.0,0,0,0,0,3.723488,3.723488
102,ESP-La Liga,2425,Barcelona,Pablo Torre,4,2024,148,11025,M S,10,...,3,0.295473,1,0.936051,6,8,0,0,3.322906,2.876598
103,ESP-La Liga,2425,Barcelona,Pau Cubarsí,4,2024,148,12005,D S,35,...,0,0.935693,3,1.536077,8,9,3,0,17.255912,17.147911
104,ESP-La Liga,2425,Barcelona,Pau Victor,4,2024,148,10953,F S,21,...,2,2.967216,1,0.876985,14,8,2,0,4.459078,0.753245
105,ESP-La Liga,2425,Barcelona,Pedri,4,2024,148,8935,M S,37,...,4,2.510431,5,7.806791,24,70,3,0,31.426336,23.621034
106,ESP-La Liga,2425,Barcelona,Raphinha,4,2024,148,8026,F M S,36,...,16,17.77944,10,13.527044,114,91,4,0,39.282579,13.650435
107,ESP-La Liga,2425,Barcelona,Robert Lewandowski,4,2024,148,227,F S,34,...,24,26.441228,2,2.475299,115,18,1,0,29.24278,6.659355
108,ESP-La Liga,2425,Barcelona,Ronald Araújo,4,2024,148,8091,D S,12,...,1,1.166387,1,0.486634,4,4,2,0,4.386616,3.893246
109,ESP-La Liga,2425,Barcelona,Sergi Domínguez,4,2024,148,12823,D S,3,...,0,0.0,0,0.0,0,0,1,0,2.077914,2.077914
110,ESP-La Liga,2425,Barcelona,Wojciech Szczesny,4,2024,148,1244,GK,15,...,0,0.0,0,0.0,0,0,1,0,5.236225,5.236225
111,ESP-La Liga,2425,Barcelona,Álex Balde,4,2024,148,9805,D S,32,...,0,0.546798,4,3.656254,12,26,2,0,19.236092,17.114045

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590 entries, 0 to 589
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   league        590 non-null    object
 1   season        590 non-null    object
 2   team          590 non-null    object
 3   player        590 non-null    object
 4   league_id     590 non-null    string
 5   season_id     590 non-null    Int64
 6   team_id       590 non-null    Int64
 7   player_id     590 non-null    Int64
 8   position      590 non-null    string
 9   matches       590 non-null    Int64
 10  minutes       590 non-null    Int64
 11  goals         590 non-null    Int64
 12  xg            590 non-null    Float64
 13  np_goals      590 non-null    Int64
 14  np_xg         590 non-null    Float64
 15  assists       590 non-null    Int64
 16  xa            590 non-null    Float64
 17  shots         590 non-null    Int64
 18  key_passes    590 non-null    Int64
 19  yellow_cards  590 non-null    Int64
 20  red_cards     590 non-null    Int64
 21  xg_chain      590 non-null    Float64
 22  xg_buildup    590 non-null    Float64
dtypes: Float64(5), Int64(12), object(4), string(2)
memory usage: 115.9+ KB

In [4]:
import requests


class SofaScoreClient:
    """
    Client for retrieving player information from SofaScore API.
    """

    BASE_URL = "https://www.sofascore.com/api/v1"

    HEADERS = {
        "User-Agent": "Mozilla/5.0",
        "Referer": "https://www.sofascore.com/"
    }

    def search_player(self, player_name: str):
        """
        Search player and return player ID.
        """

        url = f"{self.BASE_URL}/search/all?q={player_name}"

        res = requests.get(url, headers=self.HEADERS, timeout=5)

        if res.status_code != 200:
            return None

        results = res.json().get("results", [])

        for r in results:
            if r.get("type") == "player":
                return r["entity"]["id"]

        return None

    def get_player_details(self, player_id: int):

        url = f"{self.BASE_URL}/player/{player_id}"

        res = requests.get(url, headers=self.HEADERS, timeout=5)

        if res.status_code != 200:
            return None

        return res.json().get("player", None)

    def get_player_info(self, player_name: str):
        """
        Complete player information pipeline.
        """

        player_id = self.search_player(player_name)

        if not player_id:
            return None

        p_data = self.get_player_details(player_id)
        if not p_data:
            return None
        return {
            'name': p_data.get('name'),
            'birth_ts': p_data.get('dateOfBirthTimestamp'),
            'height': p_data.get('height'),
            'weight': p_data.get('weight'),
            'preferred_foot': p_data.get('preferredFoot'),
            'nationality': p_data.get('country', {}).get('name'),
            'position': p_data.get('position'),
            'detailed_positions': p_data.get('positionsDetailed', []),
            'market_value_current': p_data.get('proposedMarketValue'),
            'contract_until_ts': p_data.get('contractUntilTimestamp'),
            'popularity_score': p_data.get('userCount')
        }

In [5]:
client = SofaScoreClient()

player = client.get_player_info("Pedri")

print(player)

{'name': 'Pedri', 'birth_ts': 1038182400, 'height': 174, 'weight': 60, 'preferred_foot': 'Right', 'nationality': 'Spain', 'position': 'M', 'detailed_positions': ['MC', 'DM'], 'market_value_current': 153000000, 'contract_until_ts': 1909008000, 'popularity_score': 676309}

In [27]:
# Force le rechargement des modules à chaque exécution
%load_ext autoreload
%autoreload 2

In [14]:
import pandas as pd
from src.extract.FootballDataExtractor import FootballDataOrchestrator
from src.transform.football_transformer import DataTransformer, FeatureEngineer
import logging
# 0. Configuration pour voir l'avancement dans la console
logging.basicConfig(level=logging.INFO)
# ==========================================
# 1. EXTRACTION
# ==========================================
print("=== DEBUT EXTRACTION ===")
# On teste juste sur la Liga de la saison actuelle (24/25)
orchestrator = FootballDataOrchestrator(leagues=["ESP-La Liga"], seasons=["2425"])
# Lancement : ça va extraire depuis Understat et enrichir avec SofaScore
df_raw = orchestrator.run_full_extraction()
print(f"\n✅ Lignes brutes extraites : {len(df_raw)}")
display(df_raw.head(3))
# ==========================================
# 2. TRANSFORMATION
# ==========================================
print("\n=== DEBUT TRANSFORMATION ===")
transformer = DataTransformer()
engineer = FeatureEngineer()
# Nettoyage et typage strict des données (String, Int64, Float64)
df_clean = transformer.clean_data(df_raw)
# Création de toutes les KPIs (per_90, efficiency, collective, value)
df_final = engineer.apply_all_features(df_clean)
print(f"\n✅ Lignes transformées : {len(df_final)}")
print("\n🔍 Types des colonnes de la Table Finale (stricts pour PostgreSQL) :")
print(df_final.dtypes)
print("\n🚀 Aperçu du DataFrame Final prêt pour le Staging : ")
display(df_final.head(5))

=== DEBUT EXTRACTION ===

--- [START] ESP-La Liga | Saison 2425 ---

[03/13/26 10:20:46] INFO     Saving cached data to                                                   ]8;id=579125;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=686560;file://c:\Users\User\Desktop\detect-football-talents\.venv\Lib\site-packages\soccerdata\_common.py#249\249]8;;\
                             C:\Users\User\Desktop\detect-football-talents\data\soccerdata_cache

Enrichissement de 590 joueurs en cours...
--- [OK] 590 joueurs traités ---

✅ Lignes brutes extraites : 590

,league,season,team,player,league_id,season_id,team_id,player_id,position,matches,...,birth_ts,height,weight,preferred_foot,nationality,position_current,detailed_positions_current,market_value_current,contract_until_ts_current,popularity_score_current
0,ESP-La Liga,2425,Alaves,Abdelkabir Abqar,4,2024,158,9297,D,29,...,9.210240e+08,188.0,NaN,Right,Morocco,D,[DC],5700000.0,1.845936e+09,4075.0
1,ESP-La Liga,2425,Alaves,Abderrahmane Rebbach,4,2024,158,11825,F M S,8,...,9.027936e+08,176.0,NaN,Right,Algeria,M,[LW],1500000.0,1.845936e+09,1287.0
2,ESP-La Liga,2425,Alaves,Adrián Pica,4,2024,158,12718,D S,9,...,1.019693e+09,190.0,NaN,Right,Spain,D,[DC],1000000.0,1.782778e+09,85.0

=== DEBUT TRANSFORMATION ===

[03/13/26 10:25:36] INFO     Doublons supprimés: 0                                       ]8;id=983540;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=309088;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#25\25]8;;\

[03/13/26 10:25:37] INFO     Métriques per 90 calculées                                 ]8;id=850055;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=467603;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#203\203]8;;\

                    INFO     Métriques d'efficacité calculées                           ]8;id=807955;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=502937;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#234\234]8;;\

                    INFO     Métriques collectives calculées                            ]8;id=155739;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=721781;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#257\257]8;;\

                    INFO     Métriques de valeur calculées                              ]8;id=291979;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=941697;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#283\283]8;;\

✅ Lignes transformées : 590

🔍 Types des colonnes de la Table Finale (stricts pour PostgreSQL) :
league                        string[python]
season                        string[python]
team                          string[python]
player                        string[python]
league_id                     string[python]
season_id                              Int64
team_id                                Int64
player_id                              Int64
position                      string[python]
matches                                Int64
minutes                                Int64
goals                                  Int64
xg                                   Float64
np_goals                               Int64
np_xg                                Float64
assists                                Int64
xa                                   Float64
shots                                  Int64
key_passes                             Int64
yellow_cards                           Int64
red_cards                              Int64
xg_chain                             Float64
xg_buildup                           Float64
name_sofascore                        object
birth_ts                             float64
height                                 Int64
weight                                 Int64
preferred_foot                        object
nationality                           object
position_current                      object
detailed_positions_current            object
market_value_current                 Float64
contract_until_ts_current            float64
popularity_score_current             Float64
position_standard                     object
position_description                  object
player_age_at_season                 float64
country                               object
contract_end_date_current             object
goals_per_90                         Float64
xg_per_90                            Float64
np_goals_per_90                      Float64
np_xg_per_90                         Float64
assists_per_90                       Float64
xa_per_90                            Float64
shots_per_90                         Float64
key_passes_per_90                    Float64
involvement_per_90                   Float64
finishing_efficiency                 Float64
np_finishing_efficiency              Float64
playmaking_efficiency                Float64
shot_conversion                      Float64
involvement_index                    Float64
direct_contribution                    Int64
expected_contribution                Float64
offensive_volume                       Int64
value_per_goal                       Float64
value_per_xg                         Float64
value_per_contribution               Float64
dtype: object

🚀 Aperçu du DataFrame Final prêt pour le Staging :

,league,season,team,player,league_id,season_id,team_id,player_id,position,matches,...,np_finishing_efficiency,playmaking_efficiency,shot_conversion,involvement_index,direct_contribution,expected_contribution,offensive_volume,value_per_goal,value_per_xg,value_per_contribution
0,ESP-La Liga,2425,Alaves,Abdelkabir Abqar,4,2024,158,9297,D,29,...,0.0,4.2,0.0,5.648,1,1.096,20,0.0,6644906.0,5700000.0
1,ESP-La Liga,2425,Alaves,Abderrahmane Rebbach,4,2024,158,11825,F M S,8,...,0.0,0.0,0.0,1.822,0,0.603,12,0.0,4574565.0,0.0
2,ESP-La Liga,2425,Alaves,Adrián Pica,4,2024,158,12718,D S,9,...,0.0,0.0,0.0,1.879,0,0.663,5,0.0,1665279.0,0.0
3,ESP-La Liga,2425,Alaves,Adrián Rodríguez,4,2024,158,10272,GK S,2,...,0.0,0.0,0.0,0.075,0,0.0,0,0.0,0.0,0.0
4,ESP-La Liga,2425,Alaves,Aleksander Sedlar,4,2024,158,7845,D S,9,...,0.0,0.0,0.0,0.339,0,0.018,1,0.0,14525140.0,0.0

In [73]:
# Nettoyage et typage strict des données (String, Int64, Float64)
df_clean = transformer.clean_data(df_raw)
# Création de toutes les KPIs (per_90, efficiency, collective, value)
df_final = engineer.apply_all_features(df_clean)

[03/13/26 20:31:36] INFO     Doublons supprimés: 0                                       ]8;id=775936;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=660051;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#25\25]8;;\

                    INFO     Métriques per 90 calculées                                 ]8;id=812738;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=826127;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#203\203]8;;\

                    INFO     Métriques d'efficacité calculées                           ]8;id=137018;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=130713;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#234\234]8;;\

                    INFO     Métriques collectives calculées                            ]8;id=764623;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=999313;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#257\257]8;;\

                    INFO     Métriques de valeur calculées                              ]8;id=108084;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py\football_transformer.py]8;;\:]8;id=559189;file://c:\Users\User\Desktop\detect-football-talents\src\transform\football_transformer.py#283\283]8;;\

In [9]:
pd.set_option('display.max_columns', None)

In [45]:
df_raw.to_csv("raw_liga_fina.csv")

In [17]:
df_final.to_csv("liga_data_final.csv")

In [12]:
import pandas as pd
from src.transform.football_transformer import DataTransformer, FeatureEngineer
transformer= DataTransformer()
engineer = FeatureEngineer()
df_raw = pd.read_csv("raw_liga_fina.csv", index_col=0)
# Nettoyage et typage strict des données (String, Int64, Float64)
df_clean = transformer.clean_data(df_raw)
# Création de toutes les KPIs (per_90, efficiency, collective, value)
df_final = engineer.apply_all_features(df_clean)

INFO:src.transform.football_transformer.DataTransformer:Doublons supprimés: 0
INFO:src.transform.football_transformer.FeatureEngineer:Métriques per 90 calculées
INFO:src.transform.football_transformer.FeatureEngineer:Métriques d'efficacité calculées
INFO:src.transform.football_transformer.FeatureEngineer:Métriques collectives calculées
INFO:src.transform.football_transformer.FeatureEngineer:Métriques de valeur calculées

In [13]:
#& (df_final["goals"] > 3)
df_final[(df_final["team"] == "Barcelona") ]

,league,season,team,player,league_id,season_id,team_id,player_id,position,matches,minutes,goals,xg,np_goals,np_xg,assists,xa,shots,key_passes,yellow_cards,red_cards,xg_chain,xg_buildup,name_sofascore,birth_ts,height,weight,preferred_foot,nationality,position_current,detailed_positions_current,market_value_current,contract_until_ts_current,popularity_score_current,position_standard,position_description,player_age_at_season,country,contract_end_date_current,goals_per_90,xg_per_90,np_goals_per_90,np_xg_per_90,assists_per_90,xa_per_90,shots_per_90,key_passes_per_90,involvement_per_90,finishing_efficiency,np_finishing_efficiency,playmaking_efficiency,shot_conversion,involvement_index,direct_contribution,expected_contribution,offensive_volume,value_per_goal,value_per_xg,value_per_contribution
84,ESP-La Liga,2425,Barcelona,Andreas Christensen,4,2024,148,200,D S,5,239,0,0.0332,0,0.0332,0,0.0402,1,1,3,0,1.4766,1.4766,Andreas Christensen,8.290944e+08,188,78,Right,Denmark,D,['DC'],9600000.0,1.782778e+09,63289.0,Defender,Defender (secondary role / versatile),28.0,ESP,2026-06-30,0.0,0.013,0.0,0.013,0.0,0.015,0.377,0.377,1.112,0.0,0.0,0.0,0.0,2.953,0,0.073,2,0.0,289156627.0,0.0
85,ESP-La Liga,2425,Barcelona,Anssumane Fati,4,2024,148,7967,M S,6,228,0,1.1018,0,1.1018,0,0.1239,12,4,1,0,1.8863,0.81,NaN,0.000000e+00,0,0,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,Midfielder,Midfielder (secondary/attacking),0.0,ESP,NaT,0.0,0.435,0.0,0.435,0.0,0.049,4.737,1.579,1.064,0.0,0.0,0.0,0.0,2.696,0,1.226,16,0.0,0.0,0.0
86,ESP-La Liga,2425,Barcelona,Dani Olmo,4,2024,148,8292,M S,25,1221,10,6.6381,8,5.1516,4,3.8517,42,27,1,0,17.1268,9.9389,Dani Olmo,8.944992e+08,179,70,Right,Spain,M,"['AM', 'MC']",58000000.0,1.909008e+09,187740.0,Midfielder,Midfielder (secondary/attacking),26.0,ESP,2030-06-30,0.737,0.489,0.59,0.38,0.295,0.284,3.096,1.99,1.995,1.506,1.553,1.039,0.238,27.066,14,10.49,69,5800000.0,8737440.0,4142857.0
87,ESP-La Liga,2425,Barcelona,Daniel Rodríguez,4,2024,148,11634,M,1,37,0,0.0413,0,0.0413,0,0.0,2,0,0,0,0.3061,0.2647,Alvaro Daniel Rodriguez Munoz,0.000000e+00,0,0,NaN,NaN,M,[],0.0,0.000000e+00,28.0,Midfielder,Midfielder (central),0.0,ESP,NaT,0.0,0.1,0.0,0.1,0.0,0.0,4.865,0.0,1.388,0.0,0.0,0.0,0.0,0.571,0,0.041,2,0.0,0.0,0.0
88,ESP-La Liga,2425,Barcelona,Eric Garcia,4,2024,148,8045,D M S,29,1532,2,2.3549,2,2.3549,3,1.0125,14,7,4,0,12.8746,12.2904,Eric García,9.789984e+08,182,79,Right,Spain,D,"['DC', 'DR']",29000000.0,1.940544e+09,58637.0,Defender,Defender / Defensive Midfielder,23.0,ESP,2031-06-30,0.117,0.138,0.117,0.138,0.176,0.059,0.822,0.411,1.478,0.849,0.849,2.963,0.143,25.165,5,3.367,21,14500000.0,12314748.0,5800000.0
89,ESP-La Liga,2425,Barcelona,Fermín López,4,2024,148,11822,M S,28,1224,6,4.7566,6,4.7566,5,4.7123,41,29,4,1,15.6507,7.8535,Fermín López,1.052611e+09,176,0,Right,Spain,M,"['AM', 'MC']",72000000.0,1.940544e+09,180912.0,Midfielder,Midfielder (secondary/attacking),21.0,ESP,2031-06-30,0.441,0.35,0.441,0.35,0.368,0.346,3.015,2.132,1.728,1.261,1.261,1.061,0.146,23.504,11,9.469,70,12000000.0,15136862.0,6545455.0
90,ESP-La Liga,2425,Barcelona,Ferrán Torres,4,2024,148,6441,F M S,27,1093,10,9.6824,10,9.6824,6,3.5562,48,19,1,1,14.0588,2.258,Ferran Torres,9.517824e+08,185,77,Right,Spain,F,"['ST', 'LW', 'RW']",54000000.0,1.814314e+09,144014.0,Forward,Forward / Winger / Attacking Midfielder,24.0,ESP,2027-06-30,0.823,0.797,0.823,0.797,0.494,0.293,3.952,1.565,1.344,1.033,1.033,1.687,0.208,16.317,16,13.239,67,5400000.0,5577130.0,3375000.0
91,ESP-La Liga,2425,Barcelona,Frenkie de Jong,4,2024,148,7781,M S,26,1105,2,1.0243,2,1.0243,2,2.3029,5,21,3,0,11.6369,8.7153,Frenkie de Jong,8.633952e+08,180,70,Right,Netherlands,M,"['MC', 'DM']",42000000.0,1.877472e+09,202871.0,Midfielder,Midfielder (secondary/attacking),27.0,ESP,2029-06-30,0.163,0.083,0.163,0.083,0.163,0.188,0.407,1.71,1.658,1.953,1.953,0.868,0.4,20.352,4,3.327,26,21000000.0,41003612.0,10500000.0
92,ESP-La Liga,2425,Barcelona,Gavi,4,2024,148,9804,F M S,26,1079,1,1.0601,1,1.0601,1,1.6528,11,14,4,0,7.7693,5.8416,Pablo Gavi,1.091664e+09,173,0,Right,Spain,M,['MC'],41000000.0,1.909008e+09,270785.0,Forward,Forward / Winger / Attacking Midfielder,20.0,ESP,2030-06-30,0.083,0.088,0.083,0.088,0.083,0.138,0.918,1.168,1.135,0.943,0.943,0.605,0.091,13.611,2,2.713,25,41000000.0,38675597.0,20500000.0
93,ESP-La Liga,2425,Barcelona,Gerard Martín,4,2024,148,12821,D S,28,1018,1,0.6436,1,0.6436,3,1.2958,7,12,2,0,7.371,6.1116,Gerard Martín,1.014682e+09,186,0,Left,Spain,D,"['DL', 'DC']",18200000.0,1.845936e+09,45775.0,Defender,Defender (secondary role / versatile),22.0,ESP,2028-06-30,0.088,0.057,0.088,0.057,0.265,0.115,0.619,1.061,1.192,1.554,1.554,2.315,0.143,13.483,4,1.939,19,18200000.0,28278434.0,4550000.0
94,ESP-La Liga,2425,Barcelona,Hector Fort,4,2024,148,12171,D S,17,552,0,0.2695,0,0.2695,0,1.3017,6,9,2,0,4.3817,3.5193,Hector Fort,1.154477e+09,185,77,Right,Spain,D,['DR'],11600000.0,1.782778e+09,44752.0,Defender,Defender (secondary role / versatile),18.0,ESP,2026-06-30,0.0,0.044,0.0,0.044,0.0,0.212,0.978,1.467,1.288,0.0,0.0,0.0,0.0,7.901,0,1.571,15,0.0,43042672.0,0.0
95,ESP-La Liga,2425,Barcelona,Iñaki Peña,4,2024,148,7287,GK S,16,1393,0,0.0,0,0.0,0,0.0,0,0,1,0,3.9061,3.9061,Iñaki Peña,9.203328e+08,185,0,Right,Spain,G,['GK'],7300000.0,1.782778e+09,44622.0,Goalkeeper,Goalkeeper (substitute/secondary),25.0,ESP,2026-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.505,0.0,0.0,0.0,0.0,7.812,0,0.0,0,0.0,0.0,0.0
96,ESP-La Liga,2425,Barcelona,Iñigo Martínez,4,2024,148,2484,D,28,2505,0,0.5136,0,0.5136,4,2.248,13,16,5,0,20.0492,19.1128,Iñigo Martínez,6.744384e+08,181,77,Left,Spain,D,['DC'],4600000.0,1.782778e+09,64851.0,Defender,Defender (generic),33.0,ESP,2026-06-30,0.0,0.018,0.0,0.018,0.144,0.081,0.467,0.575,1.407,0.0,0.0,1.779,0.0,39.162,4,2.762,29,0.0,8956386.0,1150000.0
97,ESP-La Liga,2425,Barcelona,Jules Koundé,4,2024,148,6433,D S,32,2606,2,2.7438,2,2.7438,3,4.134,18,32,4,0,24.0963,20.2743,Jules Koundé,9.108288e+08,180,70,Right,France,D,['DR'],69000000.0,1.909008e+09,149309.0,Defender,Defender (secondary role / versatile),26.0,ESP,2030-06-30,0.069,0.095,0.069,0.095,0.104,0.143,0.622,1.105,1.532,0.729,0.729,0.726,0.111,44.371,5,6.878,50,34500000.0,25147606.0,13800000.0
98,ESP-La Liga,2425,Barcelona,Lamine Yamal,4,2024,148,11527,F M S,35,2879,9,11.593,9,11.593,13,14.4665,144,64,3,0,38.3079,18.0032,Lamine Yamal,1.184285e+09,180,0,Left,Spain,M,['RW'],215000000.0,1.940544e+09,1783049.0,Forward,Forward / Winger / Attacking Midfielder,17.0,ESP,2031-06-30,0.281,0.362,0.281,0.362,0.406,0.452,4.502,2.001,1.76,0.776,0.776,0.899,0.062,56.311,22,26.06,208,23888889.0,18545674.0,9772727.0
99,ESP-La Liga,2425,Barcelona,Marc Bernal,4,2024,148,12820,M,3,256,0,0.0561,0,0.0561,0,0.011,2,1,2,0,1.5139,1.4468,Marc Bernal,1.180138e+09,191,0,Left,Spain,M,['MC'],9700000.0,1.877472e+09,74733.0,Midfielder,Midfielder (central),17.0,ESP,2029-06-30,0.0,0.02,0.0,0.02,0.0,0.004,0.703,0.352,1.041,0.0,0.0,0.0,0.0,2.961,0,0.067,3,0.0,172905526.0,0.0
100,ESP-La Liga,2425,Barcelona,Marc Casadó,4,2024,148,11151,M S,23,1640,1,0.9119,1,0.9119,3,1.6349,14,9,2,1,14.538,13.5082,Marc Casadó,1.063498e+09,172,0,Right,Spain,M,"['MC', 'DM']",24000000.0,1.845936e+09,64584.0,Midfielder,Midfielder (secondary/attacking),21.0,ESP,2028-06-30,0.055,0.05,0.055,0.05,0.165,0.09,0.768,0.494,1.539,1.097,1.097,1.835,0.071,28.046,4,2.547,23,24000000.0,26318675.0,6000000.0
101,ESP-La Liga,2425,Barcelona,Marc-André ter Stegen,4,2024,148,2090,GK,8,677,0,0.0,0,0.0,0,0.0,0,0,0,0,3.7235,3.7235,Marc-André Ter Stegen,7.045920e+08,187,85,Right,Germany,G,['GK'],7300000.0,1.782778e+09,117841.0,Goalkeeper,Goalkeeper (starter),32.0,ESP,2026-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.99,0.0,0.0,0.0,0.0,7.447,0,0.0,0,0.0,0.0,0.0
102,ESP-La Liga,2425,Barcelona,Pablo Torre,4,2024,148,11025,M S,10,302,3,0.2955,3,0.2955,1,0.9361,6,8,0,0,3.3229,2.8766,Pablo Torre,1.049328e+09,173,0,Right,Spain,M,"['AM', 'MC']",4900000.0,1.877472e+09,36490.0,Midfielder,Midfielder (secondary/attacking),21.0,ESP,2029-06-30,0.894,0.088,0.894,0.088,0.298,0.279,1.788,2.384,1.848,10.152,10.152,1.068,0.5,6.2,4,1.232,14,1633333.0,16582064.0,1225000.0
103,ESP-La Liga,2425,Barcelona,Pau Cubarsí,4,2024,148,12005,D S,35,2631,0,0.9357,0,0.9357,3,1.5361,8,9,3,0,17.2559,17.1479,Pau Cubarsí,1.169424e+09,184,76,Right,Spain,D,['DC'],75000000.0,1.877472e+09,155566.0,Defender,Defender (secondary role / versatile),17.0,ESP,2029-06-30,0.0,0.032,0.0,0.032,0.103,0.053,0.274,0.308,1.177,0.0,0.0,1.953,0.0,34.404,3,2.472,17,0.0,80153895.0,25000000.0
104,ESP-La Liga,2425,Barcelona,Pau Victor,4,2024,148,10953,F S,21,273,2,2.9672,2,2.9672,1,0.877,14,8,2,0,4.4591,0.7532,Pau Víctor,1.006819e+09,182,0,Right,Spain,F,['ST'],9600000.0,1.909008e+09,37707.0,Forward,Striker / Centre Forward,23.0,ESP,2030-06-30,0.659,0.978,0.659,0.978,0.33,0.289,4.615,2.637,1.718,0.674,0.674,1.14,0.143,5.212,3,3.844,22,4800000.0,3235373.0,3200000.0
105,ESP-La Liga,2425,Barcelona,Pedri,4,2024,148,8935,M S,37,2941,4,2.5104,4,2.5104,5,7.8068,24,70,3,0,31.4263,23.621,Pedri,1.038182e+09,174,60,Right,Spain,M,"['MC', 'DM']",153000000.0,1.909008e+09,682385.0,Midfielder,Midfielder (secondary/attacking),22.0,ESP,2030-06-30,0.122,0.077,0.122,0.077,0.153,0.239,0.734,2.142,1.685,1.593,1.593,0.64,0.167,55.047,9,10.317,94,38250000.0,60946463.0,17000000.0
106,ESP-La Liga,2425,Barcelona,Raphinha,4,2024,148,8026,F M S,36,2862,18,19.266,16,17.7794,10,13.527,114,91,4,0,39.2826,13.6504,Raphinha,8.505216e+08,176,68,Left,Brazil,M,['LW'],72000000.0,1.845936e+09,918043.0,Forward,Forward / Winger / Attacking Midfielder,28.0,ESP,2028-06-30,0.566,0.606,0.503,0.559,0.314,0.425,3.585,2.862,1.665,0.934,0.9,0.739,0.158,52.933,28,32.793,205,4000000.0,3737154.0,2571429.0
107,ESP-La Liga,2425,Barcelona,Robert Lewandowski,4,2024,148,227,F S,34,2716,27,29.4143,24,26.4412,2,2.4753,115,18,1,0,29.2428,6.6594,Robert Lewandowski,5.881248e+08,186,79,Right,Poland,F,['ST'],8400000.0,1.782778e+09,583333.0,Forward,Striker / Centre Forward,36.0,ESP,2026-06-30,0.895,0.975,0.795,0.876,0.066,0.082,3.811,0.596,1.19,0.918,0.908,0.808,0.235,35.902,29,31.89,133,311111.0,285575.0,289655.0
108,ESP-La Liga,2425,Barcelona,Ronald Araújo,4,2024,148,8091,D S,12,771,1,1.1664,1,1.1664,1,0.4866,4,4,2,0,4.3866,3.8932,Ronald Araújo,9.207648e+08,191,79,Right,Uruguay,D,['DC'],27000000.0,1.940544e+09,134726.0,Defender,Defender (secondary role / versatile),25.0,ESP,2031-06-30,0.117,0.136,0.117,0.136,0.117,0.057,0.467,0.467,0.967,0.857,0.857,2.055,0.25,8.28,2,1.653,8,27000000.0,23148148.0,13500000.0
109,ESP-La Liga,2425,Barcelona,Sergi Domínguez,4,2024,148,12823,D S,3,177,0,0.0,0,0.0,0,0.0,0,0,1,0,2.0779,2.0779,Sergi Domínguez,1.112314e+09,191,0,Right,Spain,D,['DC'],2400000.0,1.877472e+09,5955.0,Defender,Defender (secondary role / versatile),19.0,ESP,2029-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.113,0.0,0.0,0.0,0.0,4.156,0,0.0,0,0.0,0.0,0.0
110,ESP-La Liga,2425,Barcelona,Wojciech Szczesny,4,2024,148,1244,GK,15,1350,0,0.0,0,0.0,0,0.0,0,0,1,0,5.2362,5.2362,Wojciech Szczęsny,6.403968e+08,196,84,Right,Poland,G,['GK'],820000.0,1.814314e+09,94565.0,Goalkeeper,Goalkeeper (starter),34.0,ESP,2027-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.698,0.0,0.0,0.0,0.0,10.472,0,0.0,0,0.0,0.0,0.0
111,ESP-La Liga,2425,Barcelona,Álex Balde,4,2024,148,9805,D S,32,2303,0,0.5468,0,0.5468,4,3.6563,12,26,2,0,19.2361,17.114,Alejandro Balde,1.066435e+09,175,0,Left,Spain,D,['DL'],66000000.0,1.845936e+09,131436.0,Defender,Defender (secondary role / versatile),21.0,ESP,2028-06-30,0.0,0.021,0.0,0.021,0.156,0.143,0.469,1.016,1.421,0.0,0.0,1.094,0.0,36.35,4,4.203,38,0.0,120702268.0,16500000.0

In [18]:
df_final[(df_final["team"] == "Real Madrid") & (df_final["contract_end_date_current"].isna())]

,league,season,team,player,league_id,season_id,team_id,player_id,position,matches,minutes,goals,xg,np_goals,np_xg,assists,xa,shots,key_passes,yellow_cards,red_cards,xg_chain,xg_buildup,name_sofascore,birth_ts,height,weight,preferred_foot,nationality,position_current,detailed_positions_current,market_value_current,contract_until_ts_current,popularity_score_current,position_standard,position_description,player_age_at_season,country,contract_end_date_current,goals_per_90,xg_per_90,np_goals_per_90,np_xg_per_90,assists_per_90,xa_per_90,shots_per_90,key_passes_per_90,involvement_per_90,finishing_efficiency,np_finishing_efficiency,playmaking_efficiency,shot_conversion,involvement_index,direct_contribution,expected_contribution,offensive_volume,value_per_goal,value_per_xg,value_per_contribution
414,ESP-La Liga,2425,Real Madrid,Federico Valverde,4,2024,150,6241,D M S,36,3035,6,2.5116,6,2.5116,4,4.4067,57,39,4,0,28.0144,23.3176,Federico Valverde,901065600.0,181,0,Right,Uruguay,M,"['MC', 'DM', 'DR']",116000000.0,0.0,379405.0,Defender,Defender / Defensive Midfielder,26.0,ESP,NaT,0.178,0.074,0.178,0.074,0.119,0.131,1.69,1.157,1.522,2.389,2.389,0.908,0.105,51.332,10,6.918,96,19333333.0,46185698.0,11600000.0
422,ESP-La Liga,2425,Real Madrid,Kylian Mbappe-Lottin,4,2024,150,3423,F,34,2938,31,30.1356,24,23.4461,3,9.3941,161,51,3,1,38.3135,11.0817,NaN,0.0,0,0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Forward,Forward (generic),0.0,ESP,NaT,0.95,0.923,0.735,0.718,0.092,0.288,4.932,1.562,1.513,1.029,1.024,0.319,0.193,49.395,34,39.53,212,0.0,0.0,0.0
427,ESP-La Liga,2425,Real Madrid,Rodrygo,4,2024,150,8015,F M S,30,1965,6,4.7242,6,4.7242,5,4.0036,54,48,0,0,17.5727,11.5087,Rodrygo,978998400.0,174,0,Right,Brazil,F,"['ST', 'RW']",64000000.0,0.0,731879.0,Forward,Forward / Winger / Attacking Midfielder,23.0,ESP,NaT,0.275,0.216,0.275,0.216,0.229,0.183,2.473,2.198,1.332,1.27,1.27,1.249,0.111,29.081,11,8.728,102,10666667.0,13547267.0,5818182.0
429,ESP-La Liga,2425,Real Madrid,Vinícius Júnior,4,2024,150,7008,F M S,30,2267,11,12.7751,9,10.5452,8,8.6393,81,58,8,1,23.5002,7.6326,Vinicius Júnior,963360000.0,176,0,Right,Brazil,F,"['LW', 'ST']",156000000.0,0.0,1225139.0,Forward,Forward / Winger / Attacking Midfielder,24.0,ESP,NaT,0.437,0.507,0.357,0.419,0.318,0.343,3.216,2.303,1.236,0.861,0.853,0.926,0.136,31.133,19,21.414,139,14181818.0,12211255.0,8210526.0

In [44]:
df_final[(df_final["team"] == "Villarreal") & (df_final["contract_end_date_current"] ==0) ]

,league,season,team,player,league_id,season_id,team_id,player_id,position,matches,minutes,goals,xg,np_goals,np_xg,assists,xa,shots,key_passes,yellow_cards,red_cards,xg_chain,xg_buildup,name_sofascore,birth_ts,height,weight,preferred_foot,nationality,position_current,detailed_positions_current,market_value_current,contract_until_ts_current,popularity_score_current,position_standard,position_description,player_age_at_season,country,contract_end_date_current,goals_per_90,xg_per_90,np_goals_per_90,np_xg_per_90,assists_per_90,xa_per_90,shots_per_90,key_passes_per_90,involvement_per_90,finishing_efficiency,np_finishing_efficiency,playmaking_efficiency,shot_conversion,involvement_index,direct_contribution,expected_contribution,offensive_volume,value_per_goal,value_per_xg,value_per_contribution
566,ESP-La Liga,2425,Villarreal,Daniel Parejo,4,2024,154,2378,M S,36,2279,3,2.6434,2,1.1569,3,1.2767,14,23,8,0,12.4231,11.4997,0,0.000000e+00,0,0,0,0,0,0,0.0,0.0,0.0,Midfielder,Midfielder (secondary/attacking),0.0,ESP,0,0.118,0.104,0.079,0.046,0.118,0.05,0.553,0.908,0.945,1.135,1.729,2.35,0.214,23.923,6,3.92,37,0.0,0.0,0.0
567,ESP-La Liga,2425,Villarreal,Daniel Requena,4,2024,154,13035,S,1,4,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0.0,Daniel Jesus Requena Gorrin,7.715520e+08,0,0,0,Spain,M,,0.0,0.0,1.0,Forward,Striker,30.0,ESP,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0
573,ESP-La Liga,2425,Villarreal,Ilias Akhomach,4,2024,154,10121,M S,11,604,1,0.6074,1,0.6074,0,1.2535,17,9,1,0,3.3974,1.7413,Ilias Akhomach,1.082074e+09,175,0,Left,Morocco,M,"RW, MR",11100000.0,0.0,15647.0,Midfielder,Midfielder (secondary/attacking),20.0,ESP,0,0.149,0.091,0.149,0.091,0.0,0.187,2.533,1.341,0.766,1.646,1.646,0.0,0.059,5.139,1,1.861,26,11100000.0,18274613.0,11100000.0
579,ESP-La Liga,2425,Villarreal,Pape Alassane Gueye,4,2024,154,8696,F M S,34,2246,4,3.8907,4,3.8907,0,1.5439,54,16,4,2,10.7991,6.8009,0,0.000000e+00,0,0,0,0,0,0,0.0,0.0,0.0,Forward,Forward / Winger / Attacking Midfielder,0.0,ESP,0,0.16,0.156,0.16,0.156,0.0,0.062,2.164,0.641,0.705,1.028,1.028,0.0,0.074,17.6,4,5.435,70,0.0,0.0,0.0
582,ESP-La Liga,2425,Villarreal,Santiago Comesaña,4,2024,154,7070,M S,35,2597,4,4.7904,4,4.7904,2,2.9418,39,28,7,0,16.3233,12.0518,Santiago Galan Comesana,0.000000e+00,0,0,0,0,0,,0.0,0.0,1.0,Midfielder,Midfielder (secondary/attacking),0.0,ESP,0,0.139,0.166,0.139,0.166,0.069,0.102,1.352,0.97,0.983,0.835,0.835,0.68,0.103,28.375,6,7.732,67,0.0,0.0,0.0

In [64]:
df_final["team"].unique()

<StringArray>
[         'Alaves',   'Athletic Club', 'Atletico Madrid',       'Barcelona',
      'Celta Vigo',        'Espanyol',          'Getafe',          'Girona',
      'Las Palmas',         'Leganes',        'Mallorca',         'Osasuna',
  'Rayo Vallecano',      'Real Betis',     'Real Madrid',   'Real Sociedad',
 'Real Valladolid',         'Sevilla',        'Valencia',      'Villarreal']
Length: 20, dtype: string

In [37]:
from src.database.db_manager import DatabaseManager
from src.load.football_loader import FootballLoader
db= DatabaseManager()
loader= FootballLoader(db)
loader.load_raw_data(df_raw)

 590 lignes insérées dans raw.player_stats

In [38]:
loader.load_dimensions(df_final)

 UPSERT de 1 lignes dans staging.dim_league terminé.
 UPSERT de 1 lignes dans staging.dim_season terminé.
 UPSERT de 20 lignes dans staging.dim_team terminé.
 UPSERT de 590 lignes dans staging.dim_player terminé.
 UPSERT de 590 lignes dans staging.fact_performance terminé.

In [39]:
# 🔹 Tester l'insertion dans raw.player_stats
from sqlalchemy import text
from src.database.db_manager import DatabaseManager

# Initialisation DB
db = DatabaseManager()

with db.session_scope() as conn:
    # 1️⃣ Vérifier le nombre de lignes
    result = conn.execute(text("SELECT COUNT(*) FROM raw.player_stats"))
    row_count = result.scalar()
    print(f"✅ Nombre de lignes dans raw.player_stats : {row_count}")

    # 2️⃣ Vérifier les colonnes
    result = conn.execute(text("""
        SELECT column_name, data_type
        FROM information_schema.columns
        WHERE table_schema = 'raw' AND table_name = 'player_stats'
        ORDER BY ordinal_position
    """))
    columns = result.fetchall()
    print("\n🔹 Colonnes et types dans raw.player_stats :")
    for col_name, col_type in columns:
        print(f" - {col_name} ({col_type})")

    # 3️⃣ Afficher un échantillon de 5 lignes
    result = conn.execute(text("SELECT * FROM raw.player_stats  LIMIT 5"))
    sample_rows = result.fetchall()
    print("\n🔹 Exemple de lignes :")
    for row in sample_rows:
        print(row)

✅ Nombre de lignes dans raw.player_stats : 590

🔹 Colonnes et types dans raw.player_stats :
 - id (bigint)
 - _extracted_at (timestamp with time zone)
 - _batch_id (uuid)
 - _source (text)
 - league (text)
 - league_id (text)
 - season (text)
 - season_id (text)
 - player (text)
 - player_id (text)
 - team (text)
 - team_id (text)
 - matches (text)
 - minutes (text)
 - goals (text)
 - assists (text)
 - shots (text)
 - key_passes (text)
 - yellow_cards (text)
 - red_cards (text)
 - xg (text)
 - xa (text)
 - xg_chain (text)
 - xg_buildup (text)
 - np_goals (text)
 - np_xg (text)
 - name_sofascore (text)
 - birth_ts (text)
 - height (text)
 - weight (text)
 - preferred_foot (text)
 - nationality (text)
 - position (text)
 - position_current (text)
 - detailed_positions_current (text)
 - market_value_current (text)
 - contract_until_ts_current (text)
 - popularity_score_current (text)

🔹 Exemple de lignes :
(1, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('bc7f6fc5-aaee-44fa-adb3-ce39ca6c5e10'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Abdelkabir Abqar', '9297', 'Alaves', '158', '29', '2489', '0', '1', '12', '8', '13', '0', '0.8577928207814693', '0.2381232511252164', '2.933803543448448', '2.713847666978836', '0', '0.8577928207814693', 'Abdelkabir Abqar', '921024000.0', '188.0', None, 'Right', 'Morocco', 'D', 'D', "['DC']", '5700000.0', '1845936000.0', '4075.0')
(2, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('3d2b800d-a9d9-4d46-bfbb-6684b769beac'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Abderrahmane Rebbach', '11825', 'Alaves', '158', '8', '381', '0', '0', '6', '6', '1', '0', '0.3279373608529567', '0.2754518706351518', '1.1501923333853483', '0.6715759411454201', '0', '0.3279373608529567', 'Abderrahman Rebbach', '902793600.0', '176.0', None, 'Right', 'Algeria', 'F M S', 'M', "['LW']", '1500000.0', '1845936000.0', '1287.0')
(3, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('faef940c-3a35-474d-851b-00f0c41f7fa1'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Adrián Pica', '12718', 'Alaves', '158', '9', '489', '0', '0', '4', '1', '1', '0', '0.6004659123718739', '0.0624145939946174', '0.9397268313914536', '0.9397268313914536', '0', '0.6004659123718739', 'Adrián Pica', '1019692800.0', '190.0', None, 'Right', 'Spain', 'D S', 'D', "['DC']", '1000000.0', '1782777600.0', '85.0')
(4, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('dc7aad88-2ea8-4045-bf0d-29eb53194c25'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Adrián Rodríguez', '10272', 'Alaves', '158', '2', '120', '0', '0', '0', '0', '1', '0', '0.0', '0.0', '0.0376009717583656', '0.0376009717583656', '0', '0.0', 'Adrián Rodríguez', '976579200.0', '195.0', None, 'Right', 'Argentina', 'GK S', 'G', "['GK']", '185000.0', '1782777600.0', '226.0')
(5, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('0cdb1b47-60e9-4f40-9f33-da91e594982c'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Aleksander Sedlar', '7845', 'Alaves', '158', '9', '599', '0', '0', '1', '0', '1', '1', '0.0179237257689237', '0.0', '0.1696080192923545', '0.1696080192923545', '0', '0.0179237257689237', 'Aleksandar Sedlar', '692582400.0', '180.0', '79.0', 'Right', 'Serbia', 'D S', 'D', "['DC']", '260000.0', '1782777600.0', '219.0')

In [40]:
with db.session_scope() as conn:
    # 1️⃣ Vérifier le nombre de lignes
    result = conn.execute(text("SELECT * FROM raw.player_stats WHERE team='Barcelona'"))
    sample_rows_barca = result.fetchall()
    for row in sample_rows_barca:
        print(row)

(85, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('71b5bf80-c6fe-45ca-8c78-226b685a0a80'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Andreas Christensen', '200', 'Barcelona', '148', '5', '239', '0', '0', '1', '1', '3', '0', '0.0332164540886879', '0.04022017121315', '1.4766459465026855', '1.4766459465026855', '0', '0.0332164540886879', 'Andreas Christensen', '829094400.0', '188.0', '78.0', 'Right', 'Denmark', 'D S', 'D', "['DC']", '9600000.0', '1782777600.0', '63289.0')
(86, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('58230c0e-7005-49f9-b025-b4ec942a5515'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Anssumane Fati', '7967', 'Barcelona', '148', '6', '228', '0', '0', '12', '4', '1', '0', '1.1018417924642565', '0.1238601952791214', '1.8863119632005687', '0.8099945038557053', '0', '1.1018417924642565', None, None, None, None, None, None, 'M S', None, None, None, None, None)
(87, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('95e0384c-4b15-4706-8650-bbcef820247a'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Dani Olmo', '8292', 'Barcelona', '148', '25', '1221', '10', '4', '42', '27', '1', '0', '6.638132888823748', '3.851693106815219', '17.126844070851803', '9.938899960368872', '8', '5.151577670127153', 'Dani Olmo', '894499200.0', '179.0', '70.0', 'Right', 'Spain', 'M S', 'M', "['AM', 'MC']", '58000000.0', '1909008000.0', '187740.0')
(88, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('4753294f-7732-429f-bbd1-e4bedefd1a3c'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Daniel Rodríguez', '11634', 'Barcelona', '148', '1', '37', '0', '0', '2', '0', '0', '0', '0.0413202755153179', '0.0', '0.3060602843761444', '0.2647400200366974', '0', '0.0413202755153179', 'Alvaro Daniel Rodriguez Munoz', None, None, None, None, None, 'M', 'M', '[]', None, None, '28.0')
(89, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('94914d0a-2ad1-438a-9f90-d9c8d9070775'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Eric Garcia', '8045', 'Barcelona', '148', '29', '1532', '2', '3', '14', '7', '4', '0', '2.354891483671963', '1.012534737586975', '12.874616280198095', '12.290382117033005', '2', '2.354891483671963', 'Eric García', '978998400.0', '182.0', '79.0', 'Right', 'Spain', 'D M S', 'D', "['DC', 'DR']", '29000000.0', '1940544000.0', '58637.0')
(90, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('58954c10-8797-4dad-ae9f-f8915406bf32'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Fermín López', '11822', 'Barcelona', '148', '28', '1224', '6', '5', '41', '29', '4', '1', '4.756551628932357', '4.712301393970847', '15.650715451687574', '7.853520656004548', '6', '4.756551628932357', 'Fermín López', '1052611200.0', '176.0', None, 'Right', 'Spain', 'M S', 'M', "['AM', 'MC']", '72000000.0', '1940544000.0', '180912.0')
(91, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('6ac1cbbb-89e7-419e-be1e-0d0466242032'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Ferrán Torres', '6441', 'Barcelona', '148', '27', '1093', '10', '6', '48', '19', '1', '1', '9.682402739301324', '3.556156000122428', '14.058789663016796', '2.258015837520361', '10', '9.682402739301324', 'Ferran Torres', '951782400.0', '185.0', '77.0', 'Right', 'Spain', 'F M S', 'F', "['ST', 'LW', 'RW']", '54000000.0', '1814313600.0', '144014.0')
(92, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('f9cb9ed0-a70a-4e5d-9bd4-37be08298ac8'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Frenkie de Jong', '7781', 'Barcelona', '148', '26', '1105', '2', '2', '5', '21', '3', '0', '1.0243200585246086', '2.302895499393344', '11.636852502822876', '8.715320311486721', '2', '1.0243200585246086', 'Frenkie de Jong', '863395200.0', '180.0', '70.0', 'Right', 'Netherlands', 'M S', 'M', "['MC', 'DM']", '42000000.0', '1877472000.0', '202871.0')
(93, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('eae72cdd-6c1b-4563-bda8-3826942657ea'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Gavi', '9804', 'Barcelona', '148', '26', '1079', '1', '1', '11', '14', '4', '0', '1.0601166114211082', '1.6527631673961878', '7.769327191635966', '5.841560788452625', '1', '1.0601166114211082', 'Pablo Gavi', '1091664000.0', '173.0', None, 'Right', 'Spain', 'F M S', 'M', "['MC']", '41000000.0', '1909008000.0', '270785.0')
(94, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('a07dffa6-8f4e-48c9-b61b-6bfbad03c0af'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Gerard Martín', '12821', 'Barcelona', '148', '28', '1018', '1', '3', '7', '12', '2', '0', '0.6436223732307553', '1.2958451379090548', '7.371043564751744', '6.111580042168498', '1', '0.6436223732307553', 'Gerard Martín', '1014681600.0', '186.0', None, 'Left', 'Spain', 'D S', 'D', "['DL', 'DC']", '18200000.0', '1845936000.0', '45775.0')
(95, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('35745583-881a-4849-b44d-e5bb1b0ff8bb'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Hector Fort', '12171', 'Barcelona', '148', '17', '552', '0', '0', '6', '9', '2', '0', '0.2694935295730829', '1.30174807831645', '4.381688091903925', '3.519320610910654', '0', '0.2694935295730829', 'Hector Fort', '1154476800.0', '185.0', '77.0', 'Right', 'Spain', 'D S', 'D', "['DR']", '11600000.0', '1782777600.0', '44752.0')
(96, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('aac992fc-5dde-42c0-864a-e72e6f2be42a'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Iñaki Peña', '7287', 'Barcelona', '148', '16', '1393', '0', '0', '0', '0', '1', '0', '0.0', '0.0', '3.906119585037232', '3.906119585037232', '0', '0.0', 'Iñaki Peña', '920332800.0', '185.0', None, 'Right', 'Spain', 'GK S', 'G', "['GK']", '7300000.0', '1782777600.0', '44622.0')
(97, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('9fe9d721-6e84-4c9a-a06e-e59975c9b081'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Iñigo Martínez', '2484', 'Barcelona', '148', '28', '2505', '0', '4', '13', '16', '5', '0', '0.5136058144271374', '2.2479534801095724', '20.049223262816668', '19.11283127591014', '0', '0.5136058144271374', 'Iñigo Martínez', '674438400.0', '181.0', '77.0', 'Left', 'Spain', 'D', 'D', "['DC']", '4600000.0', '1782777600.0', '64851.0')
(98, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('3a9362c3-95d9-4595-b11e-572ea7a2f00e'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Jules Koundé', '6433', 'Barcelona', '148', '32', '2606', '2', '3', '18', '32', '4', '0', '2.743822293356061', '4.134010413661599', '24.09632397815585', '20.27425637468696', '2', '2.743822293356061', 'Jules Koundé', '910828800.0', '180.0', '70.0', 'Right', 'France', 'D S', 'D', "['DR']", '69000000.0', '1909008000.0', '149309.0')
(99, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('ea3e98f9-b134-411f-81cb-7af9d5505a35'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Lamine Yamal', '11527', 'Barcelona', '148', '35', '2879', '9', '13', '144', '64', '3', '0', '11.593033526092768', '14.466477727517486', '38.30787461996079', '18.00324920192361', '9', '11.593033526092768', 'Lamine Yamal', '1184284800.0', '180.0', None, 'Left', 'Spain', 'F M S', 'M', "['RW']", '215000000.0', '1940544000.0', '1783049.0')
(100, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('727be2f2-ddd5-4ae9-b82b-3f5bed3de949'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Marc Bernal', '12820', 'Barcelona', '148', '3', '256', '0', '0', '2', '1', '2', '0', '0.0560634769499301', '0.0110369473695755', '1.5139116048812866', '1.4468111991882324', '0', '0.0560634769499301', 'Marc Bernal', '1180137600.0', '191.0', None, 'Left', 'Spain', 'M', 'M', "['MC']", '9700000.0', '1877472000.0', '74733.0')
(101, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('55e48bb9-71da-40a8-b800-63c94e6721cc'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Marc Casadó', '11151', 'Barcelona', '148', '23', '1640', '1', '3', '14', '9', '2', '1', '0.9119365168735384', '1.634875988587737', '14.537989675998688', '13.50816598907113', '1', '0.9119365168735384', 'Marc Casadó', '1063497600.0', '172.0', None, 'Right', 'Spain', 'M S', 'M', "['MC', 'DM']", '24000000.0', '1845936000.0', '64584.0')
(102, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('de721895-00b4-46e3-ae2e-fc3a9f57dbc6'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Marc-André ter Stegen', '2090', 'Barcelona', '148', '8', '677', '0', '0', '0', '0', '0', '0', '0.0', '0.0', '3.72348815202713', '3.72348815202713', '0', '0.0', 'Marc-André Ter Stegen', '704592000.0', '187.0', '85.0', 'Right', 'Germany', 'GK', 'G', "['GK']", '7300000.0', '1782777600.0', '117841.0')
(103, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('ddf7e5b6-71b6-4a3c-890a-c379a848e654'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Pablo Torre', '11025', 'Barcelona', '148', '10', '302', '3', '1', '6', '8', '0', '0', '0.2954732328653335', '0.9360514245927334', '3.322905655950308', '2.8765976540744305', '3', '0.2954732328653335', 'Pablo Torre', '1049328000.0', '173.0', None, 'Right', 'Spain', 'M S', 'M', "['AM', 'MC']", '4900000.0', '1877472000.0', '36490.0')
(104, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('e1b338f7-2e32-4d68-8aea-7e24bdc7a15c'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Pau Cubarsí', '12005', 'Barcelona', '148', '35', '2631', '0', '3', '8', '9', '3', '0', '0.9356927424669266', '1.5360766984522345', '17.255911896005273', '17.147910771891475', '0', '0.9356927424669266', 'Pau Cubarsí', '1169424000.0', '184.0', '76.0', 'Right', 'Spain', 'D S', 'D', "['DC']", '75000000.0', '1877472000.0', '155566.0')
(105, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('cf971bec-63d4-4e9c-92b8-19ce72d46113'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Pau Victor', '10953', 'Barcelona', '148', '21', '273', '2', '1', '14', '8', '2', '0', '2.9672163296490908', '0.8769846558570862', '4.459078095853329', '0.7532445453107357', '2', '2.9672163296490908', 'Pau Víctor', '1006819200.0', '182.0', None, 'Right', 'Spain', 'F S', 'F', "['ST']", '9600000.0', '1909008000.0', '37707.0')
(106, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('1d3489c1-e0ed-45f2-be32-2304b7f3721d'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Pedri', '8935', 'Barcelona', '148', '37', '2941', '4', '5', '24', '70', '3', '0', '2.5104309488087893', '7.80679078027606', '31.42633649148047', '23.62103444710374', '4', '2.5104309488087893', 'Pedri', '1038182400.0', '174.0', '60.0', 'Right', 'Spain', 'M S', 'M', "['MC', 'DM']", '153000000.0', '1909008000.0', '682385.0')
(107, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('9edd18ae-36dc-49fc-912d-f49a6e8e2b64'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Raphinha', '8026', 'Barcelona', '148', '36', '2862', '18', '10', '114', '91', '4', '0', '19.26599541865289', '13.527044044807552', '39.28257852047682', '13.650435471907258', '16', '17.779440259560943', 'Raphinha', '850521600.0', '176.0', '68.0', 'Left', 'Brazil', 'F M S', 'M', "['LW']", '72000000.0', '1845936000.0', '918043.0')
(108, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('9ec4f1f5-9d9c-418e-8662-74e710194cf8'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Robert Lewandowski', '227', 'Barcelona', '148', '34', '2716', '27', '2', '115', '18', '1', '0', '29.41433861851692', '2.4752993676811457', '29.242779716849327', '6.6593545116484165', '24', '26.441228091716766', 'Robert Lewandowski', '588124800.0', '186.0', '79.0', 'Right', 'Poland', 'F S', 'F', "['ST']", '8400000.0', '1782777600.0', '583333.0')
(109, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('7a2cc748-3835-4e12-af22-495368ee63ae'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Ronald Araújo', '8091', 'Barcelona', '148', '12', '771', '1', '1', '4', '4', '2', '0', '1.166387401521206', '0.4866340160369873', '4.386615861207247', '3.8932461254298687', '1', '1.166387401521206', 'Ronald Araújo', '920764800.0', '191.0', '79.0', 'Right', 'Uruguay', 'D S', 'D', "['DC']", '27000000.0', '1940544000.0', '134726.0')
(110, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('dca2efe4-e6f1-4ace-aa4c-931d7b811bd5'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Sergi Domínguez', '12823', 'Barcelona', '148', '3', '177', '0', '0', '0', '0', '1', '0', '0.0', '0.0', '2.0779144912958145', '2.0779144912958145', '0', '0.0', 'Sergi Domínguez', '1112313600.0', '191.0', None, 'Right', 'Spain', 'D S', 'D', "['DC']", '2400000.0', '1877472000.0', '5955.0')
(111, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('76f7705b-1ab5-4a00-8c3f-8b839c5698c9'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Wojciech Szczesny', '1244', 'Barcelona', '148', '15', '1350', '0', '0', '0', '0', '1', '0', '0.0', '0.0', '5.236224640160799', '5.236224640160799', '0', '0.0', 'Wojciech Szczęsny', '640396800.0', '196.0', '84.0', 'Right', 'Poland', 'GK', 'G', "['GK']", '820000.0', '1814313600.0', '94565.0')
(112, datetime.datetime(2026, 3, 14, 1, 7, 38, 752455, tzinfo=datetime.timezone.utc), UUID('d80d39c3-ad91-47ec-99ed-c5ec8f35c32e'), 'understat+sofascore', 'ESP-La Liga', '4', '2425', '2024', 'Álex Balde', '9805', 'Barcelona', '148', '32', '2303', '0', '4', '12', '26', '2', '0', '0.5467977644875646', '3.6562538016587496', '19.236092265695333', '17.1140445061028', '0', '0.5467977644875646', 'Alejandro Balde', '1066435200.0', '175.0', None, 'Left', 'Spain', 'D S', 'D', "['DL']", '66000000.0', '1845936000.0', '131436.0')

In [20]:
df_final[df_final["player"] == "David López"]

,league,season,team,player,league_id,season_id,team_id,player_id,position,matches,minutes,goals,xg,np_goals,np_xg,assists,xa,shots,key_passes,yellow_cards,red_cards,xg_chain,xg_buildup,name_sofascore,birth_ts,height,weight,preferred_foot,nationality,position_current,detailed_positions_current,market_value_current,contract_until_ts_current,popularity_score_current,position_standard,position_description,player_age_at_season,country,contract_end_date_current,goals_per_90,xg_per_90,np_goals_per_90,np_xg_per_90,assists_per_90,xa_per_90,shots_per_90,key_passes_per_90,involvement_per_90,finishing_efficiency,np_finishing_efficiency,playmaking_efficiency,shot_conversion,involvement_index,direct_contribution,expected_contribution,offensive_volume,value_per_goal,value_per_xg,value_per_contribution
207,ESP-La Liga,2425,Girona,David López,4,2024,223,1857,D S,29,2429,1,1.017,1,1.017,1,0.776,12,4,4,0,8.8944,8.7978,David López,623894400.0,185,81,Right,Spain,D,['DC'],730000.0,1.782778e+09,522.0,Defender,Defender (secondary role / versatile),35.0,ESP,2026-06-30,0.037,0.038,0.037,0.038,0.037,0.029,0.445,0.148,0.656,0.983,0.983,1.289,0.083,17.692,2,1.793,16,730000.0,717797.0,365000.0
295,ESP-La Liga,2425,Mallorca,David López,4,2024,239,12074,D,2,172,0,0.0,0,0.0,0,0.0,0,0,0,0,0.012,0.012,David López,623894400.0,185,81,Right,Spain,D,['DC'],730000.0,1.782778e+09,522.0,Defender,Defender (generic),35.0,ESP,2026-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.013,0.0,0.0,0.0,0.0,0.024,0,0.0,0,0.0,0.0,0.0

In [45]:
with db.session_scope() as conn:
    # 1️⃣ Vérifier le nombre de lignes
# Correction de la syntaxe SQL
    stm = """
        SELECT 
            p.player,
            t.team,
            f.*
        FROM staging.dim_player AS p
        JOIN staging.fact_performance AS f ON f.player_id = p.player_id
        JOIN staging.dim_team AS t ON f.team_id = t.team_id
        WHERE t.team = 'Barcelona'
        
    """ 
    result = conn.execute(text(stm))
    sample_rows_barca = result.fetchall()
    for row in sample_rows_barca:
        print(row)

('Andreas Christensen', 'Barcelona', 85, 200, 148, 2024, '4', 5, 239, 0, 0, 1, 1, 3, 0, 0, Decimal('0.0332'), Decimal('0.0402'), Decimal('1.4766'), Decimal('1.4766'), Decimal('0.0332'), Decimal('0.000'), Decimal('0.013'), Decimal('0.000'), Decimal('0.013'), Decimal('0.000'), Decimal('0.015'), Decimal('0.377'), Decimal('0.377'), Decimal('1.112'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('2.953'), 0, Decimal('0.073'), 2, 28, Decimal('9600000.00'), 63289, datetime.date(2026, 6, 30), Decimal('0.00'), Decimal('289156627.00'), Decimal('0.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Anssumane Fati', 'Barcelona', 86, 7967, 148, 2024, '4', 6, 228, 0, 0, 12, 4, 1, 0, 0, Decimal('1.1018'), Decimal('0.1239'), Decimal('1.8863'), Decimal('0.8100'), Decimal('1.1018'), Decimal('0.000'), Decimal('0.435'), Decimal('0.000'), Decimal('0.435'), Decimal('0.000'), Decimal('0.049'), Decimal('4.737'), Decimal('1.579'), Decimal('1.064'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('2.696'), 0, Decimal('1.226'), 16, 0, Decimal('0.00'), 0, None, Decimal('0.00'), Decimal('0.00'), Decimal('0.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Dani Olmo', 'Barcelona', 87, 8292, 148, 2024, '4', 25, 1221, 10, 4, 42, 27, 1, 0, 8, Decimal('6.6381'), Decimal('3.8517'), Decimal('17.1268'), Decimal('9.9389'), Decimal('5.1516'), Decimal('0.737'), Decimal('0.489'), Decimal('0.590'), Decimal('0.380'), Decimal('0.295'), Decimal('0.284'), Decimal('3.096'), Decimal('1.990'), Decimal('1.995'), Decimal('1.5060'), Decimal('1.5530'), Decimal('1.0390'), Decimal('0.2380'), Decimal('27.066'), 14, Decimal('10.490'), 69, 26, Decimal('58000000.00'), 187740, datetime.date(2030, 6, 30), Decimal('5800000.00'), Decimal('8737440.00'), Decimal('4142857.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Daniel Rodríguez', 'Barcelona', 88, 11634, 148, 2024, '4', 1, 37, 0, 0, 2, 0, 0, 0, 0, Decimal('0.0413'), Decimal('0.0000'), Decimal('0.3061'), Decimal('0.2647'), Decimal('0.0413'), Decimal('0.000'), Decimal('0.100'), Decimal('0.000'), Decimal('0.100'), Decimal('0.000'), Decimal('0.000'), Decimal('4.865'), Decimal('0.000'), Decimal('1.388'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.571'), 0, Decimal('0.041'), 2, 0, Decimal('0.00'), 28, None, Decimal('0.00'), Decimal('0.00'), Decimal('0.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Eric Garcia', 'Barcelona', 89, 8045, 148, 2024, '4', 29, 1532, 2, 3, 14, 7, 4, 0, 2, Decimal('2.3549'), Decimal('1.0125'), Decimal('12.8746'), Decimal('12.2904'), Decimal('2.3549'), Decimal('0.117'), Decimal('0.138'), Decimal('0.117'), Decimal('0.138'), Decimal('0.176'), Decimal('0.059'), Decimal('0.822'), Decimal('0.411'), Decimal('1.478'), Decimal('0.8490'), Decimal('0.8490'), Decimal('2.9630'), Decimal('0.1430'), Decimal('25.165'), 5, Decimal('3.367'), 21, 23, Decimal('29000000.00'), 58637, datetime.date(2031, 6, 30), Decimal('14500000.00'), Decimal('12314748.00'), Decimal('5800000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Fermín López', 'Barcelona', 90, 11822, 148, 2024, '4', 28, 1224, 6, 5, 41, 29, 4, 1, 6, Decimal('4.7566'), Decimal('4.7123'), Decimal('15.6507'), Decimal('7.8535'), Decimal('4.7566'), Decimal('0.441'), Decimal('0.350'), Decimal('0.441'), Decimal('0.350'), Decimal('0.368'), Decimal('0.346'), Decimal('3.015'), Decimal('2.132'), Decimal('1.728'), Decimal('1.2610'), Decimal('1.2610'), Decimal('1.0610'), Decimal('0.1460'), Decimal('23.504'), 11, Decimal('9.469'), 70, 21, Decimal('72000000.00'), 180912, datetime.date(2031, 6, 30), Decimal('12000000.00'), Decimal('15136862.00'), Decimal('6545455.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Ferrán Torres', 'Barcelona', 91, 6441, 148, 2024, '4', 27, 1093, 10, 6, 48, 19, 1, 1, 10, Decimal('9.6824'), Decimal('3.5562'), Decimal('14.0588'), Decimal('2.2580'), Decimal('9.6824'), Decimal('0.823'), Decimal('0.797'), Decimal('0.823'), Decimal('0.797'), Decimal('0.494'), Decimal('0.293'), Decimal('3.952'), Decimal('1.565'), Decimal('1.344'), Decimal('1.0330'), Decimal('1.0330'), Decimal('1.6870'), Decimal('0.2080'), Decimal('16.317'), 16, Decimal('13.239'), 67, 24, Decimal('54000000.00'), 144014, datetime.date(2027, 6, 30), Decimal('5400000.00'), Decimal('5577130.00'), Decimal('3375000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Frenkie de Jong', 'Barcelona', 92, 7781, 148, 2024, '4', 26, 1105, 2, 2, 5, 21, 3, 0, 2, Decimal('1.0243'), Decimal('2.3029'), Decimal('11.6369'), Decimal('8.7153'), Decimal('1.0243'), Decimal('0.163'), Decimal('0.083'), Decimal('0.163'), Decimal('0.083'), Decimal('0.163'), Decimal('0.188'), Decimal('0.407'), Decimal('1.710'), Decimal('1.658'), Decimal('1.9530'), Decimal('1.9530'), Decimal('0.8680'), Decimal('0.4000'), Decimal('20.352'), 4, Decimal('3.327'), 26, 27, Decimal('42000000.00'), 202871, datetime.date(2029, 6, 30), Decimal('21000000.00'), Decimal('41003612.00'), Decimal('10500000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Gavi', 'Barcelona', 93, 9804, 148, 2024, '4', 26, 1079, 1, 1, 11, 14, 4, 0, 1, Decimal('1.0601'), Decimal('1.6528'), Decimal('7.7693'), Decimal('5.8416'), Decimal('1.0601'), Decimal('0.083'), Decimal('0.088'), Decimal('0.083'), Decimal('0.088'), Decimal('0.083'), Decimal('0.138'), Decimal('0.918'), Decimal('1.168'), Decimal('1.135'), Decimal('0.9430'), Decimal('0.9430'), Decimal('0.6050'), Decimal('0.0910'), Decimal('13.611'), 2, Decimal('2.713'), 25, 20, Decimal('41000000.00'), 270785, datetime.date(2030, 6, 30), Decimal('41000000.00'), Decimal('38675597.00'), Decimal('20500000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Gerard Martín', 'Barcelona', 94, 12821, 148, 2024, '4', 28, 1018, 1, 3, 7, 12, 2, 0, 1, Decimal('0.6436'), Decimal('1.2958'), Decimal('7.3710'), Decimal('6.1116'), Decimal('0.6436'), Decimal('0.088'), Decimal('0.057'), Decimal('0.088'), Decimal('0.057'), Decimal('0.265'), Decimal('0.115'), Decimal('0.619'), Decimal('1.061'), Decimal('1.192'), Decimal('1.5540'), Decimal('1.5540'), Decimal('2.3150'), Decimal('0.1430'), Decimal('13.483'), 4, Decimal('1.939'), 19, 22, Decimal('18200000.00'), 45775, datetime.date(2028, 6, 30), Decimal('18200000.00'), Decimal('28278434.00'), Decimal('4550000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Hector Fort', 'Barcelona', 95, 12171, 148, 2024, '4', 17, 552, 0, 0, 6, 9, 2, 0, 0, Decimal('0.2695'), Decimal('1.3017'), Decimal('4.3817'), Decimal('3.5193'), Decimal('0.2695'), Decimal('0.000'), Decimal('0.044'), Decimal('0.000'), Decimal('0.044'), Decimal('0.000'), Decimal('0.212'), Decimal('0.978'), Decimal('1.467'), Decimal('1.288'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('7.901'), 0, Decimal('1.571'), 15, 18, Decimal('11600000.00'), 44752, datetime.date(2026, 6, 30), Decimal('0.00'), Decimal('43042672.00'), Decimal('0.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Iñaki Peña', 'Barcelona', 96, 7287, 148, 2024, '4', 16, 1393, 0, 0, 0, 0, 1, 0, 0, Decimal('0.0000'), Decimal('0.0000'), Decimal('3.9061'), Decimal('3.9061'), Decimal('0.0000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.505'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('7.812'), 0, Decimal('0.000'), 0, 25, Decimal('7300000.00'), 44622, datetime.date(2026, 6, 30), Decimal('0.00'), Decimal('0.00'), Decimal('0.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Iñigo Martínez', 'Barcelona', 97, 2484, 148, 2024, '4', 28, 2505, 0, 4, 13, 16, 5, 0, 0, Decimal('0.5136'), Decimal('2.2480'), Decimal('20.0492'), Decimal('19.1128'), Decimal('0.5136'), Decimal('0.000'), Decimal('0.018'), Decimal('0.000'), Decimal('0.018'), Decimal('0.144'), Decimal('0.081'), Decimal('0.467'), Decimal('0.575'), Decimal('1.407'), Decimal('0.0000'), Decimal('0.0000'), Decimal('1.7790'), Decimal('0.0000'), Decimal('39.162'), 4, Decimal('2.762'), 29, 33, Decimal('4600000.00'), 64851, datetime.date(2026, 6, 30), Decimal('0.00'), Decimal('8956386.00'), Decimal('1150000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Jules Koundé', 'Barcelona', 98, 6433, 148, 2024, '4', 32, 2606, 2, 3, 18, 32, 4, 0, 2, Decimal('2.7438'), Decimal('4.1340'), Decimal('24.0963'), Decimal('20.2743'), Decimal('2.7438'), Decimal('0.069'), Decimal('0.095'), Decimal('0.069'), Decimal('0.095'), Decimal('0.104'), Decimal('0.143'), Decimal('0.622'), Decimal('1.105'), Decimal('1.532'), Decimal('0.7290'), Decimal('0.7290'), Decimal('0.7260'), Decimal('0.1110'), Decimal('44.371'), 5, Decimal('6.878'), 50, 26, Decimal('69000000.00'), 149309, datetime.date(2030, 6, 30), Decimal('34500000.00'), Decimal('25147606.00'), Decimal('13800000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Lamine Yamal', 'Barcelona', 99, 11527, 148, 2024, '4', 35, 2879, 9, 13, 144, 64, 3, 0, 9, Decimal('11.5930'), Decimal('14.4665'), Decimal('38.3079'), Decimal('18.0032'), Decimal('11.5930'), Decimal('0.281'), Decimal('0.362'), Decimal('0.281'), Decimal('0.362'), Decimal('0.406'), Decimal('0.452'), Decimal('4.502'), Decimal('2.001'), Decimal('1.760'), Decimal('0.7760'), Decimal('0.7760'), Decimal('0.8990'), Decimal('0.0620'), Decimal('56.311'), 22, Decimal('26.060'), 208, 17, Decimal('215000000.00'), 1783049, datetime.date(2031, 6, 30), Decimal('23888889.00'), Decimal('18545674.00'), Decimal('9772727.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Marc Bernal', 'Barcelona', 100, 12820, 148, 2024, '4', 3, 256, 0, 0, 2, 1, 2, 0, 0, Decimal('0.0561'), Decimal('0.0110'), Decimal('1.5139'), Decimal('1.4468'), Decimal('0.0561'), Decimal('0.000'), Decimal('0.020'), Decimal('0.000'), Decimal('0.020'), Decimal('0.000'), Decimal('0.004'), Decimal('0.703'), Decimal('0.352'), Decimal('1.041'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('2.961'), 0, Decimal('0.067'), 3, 17, Decimal('9700000.00'), 74733, datetime.date(2029, 6, 30), Decimal('0.00'), Decimal('172905526.00'), Decimal('0.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Marc Casadó', 'Barcelona', 101, 11151, 148, 2024, '4', 23, 1640, 1, 3, 14, 9, 2, 1, 1, Decimal('0.9119'), Decimal('1.6349'), Decimal('14.5380'), Decimal('13.5082'), Decimal('0.9119'), Decimal('0.055'), Decimal('0.050'), Decimal('0.055'), Decimal('0.050'), Decimal('0.165'), Decimal('0.090'), Decimal('0.768'), Decimal('0.494'), Decimal('1.539'), Decimal('1.0970'), Decimal('1.0970'), Decimal('1.8350'), Decimal('0.0710'), Decimal('28.046'), 4, Decimal('2.547'), 23, 21, Decimal('24000000.00'), 64584, datetime.date(2028, 6, 30), Decimal('24000000.00'), Decimal('26318675.00'), Decimal('6000000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Marc-André ter Stegen', 'Barcelona', 102, 2090, 148, 2024, '4', 8, 677, 0, 0, 0, 0, 0, 0, 0, Decimal('0.0000'), Decimal('0.0000'), Decimal('3.7235'), Decimal('3.7235'), Decimal('0.0000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.990'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('7.447'), 0, Decimal('0.000'), 0, 32, Decimal('7300000.00'), 117841, datetime.date(2026, 6, 30), Decimal('0.00'), Decimal('0.00'), Decimal('0.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Pablo Torre', 'Barcelona', 103, 11025, 148, 2024, '4', 10, 302, 3, 1, 6, 8, 0, 0, 3, Decimal('0.2955'), Decimal('0.9361'), Decimal('3.3229'), Decimal('2.8766'), Decimal('0.2955'), Decimal('0.894'), Decimal('0.088'), Decimal('0.894'), Decimal('0.088'), Decimal('0.298'), Decimal('0.279'), Decimal('1.788'), Decimal('2.384'), Decimal('1.848'), Decimal('10.1520'), Decimal('10.1520'), Decimal('1.0680'), Decimal('0.5000'), Decimal('6.200'), 4, Decimal('1.232'), 14, 21, Decimal('4900000.00'), 36490, datetime.date(2029, 6, 30), Decimal('1633333.00'), Decimal('16582064.00'), Decimal('1225000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Pau Cubarsí', 'Barcelona', 104, 12005, 148, 2024, '4', 35, 2631, 0, 3, 8, 9, 3, 0, 0, Decimal('0.9357'), Decimal('1.5361'), Decimal('17.2559'), Decimal('17.1479'), Decimal('0.9357'), Decimal('0.000'), Decimal('0.032'), Decimal('0.000'), Decimal('0.032'), Decimal('0.103'), Decimal('0.053'), Decimal('0.274'), Decimal('0.308'), Decimal('1.177'), Decimal('0.0000'), Decimal('0.0000'), Decimal('1.9530'), Decimal('0.0000'), Decimal('34.404'), 3, Decimal('2.472'), 17, 17, Decimal('75000000.00'), 155566, datetime.date(2029, 6, 30), Decimal('0.00'), Decimal('80153895.00'), Decimal('25000000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Pau Victor', 'Barcelona', 105, 10953, 148, 2024, '4', 21, 273, 2, 1, 14, 8, 2, 0, 2, Decimal('2.9672'), Decimal('0.8770'), Decimal('4.4591'), Decimal('0.7532'), Decimal('2.9672'), Decimal('0.659'), Decimal('0.978'), Decimal('0.659'), Decimal('0.978'), Decimal('0.330'), Decimal('0.289'), Decimal('4.615'), Decimal('2.637'), Decimal('1.718'), Decimal('0.6740'), Decimal('0.6740'), Decimal('1.1400'), Decimal('0.1430'), Decimal('5.212'), 3, Decimal('3.844'), 22, 23, Decimal('9600000.00'), 37707, datetime.date(2030, 6, 30), Decimal('4800000.00'), Decimal('3235373.00'), Decimal('3200000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Pedri', 'Barcelona', 106, 8935, 148, 2024, '4', 37, 2941, 4, 5, 24, 70, 3, 0, 4, Decimal('2.5104'), Decimal('7.8068'), Decimal('31.4263'), Decimal('23.6210'), Decimal('2.5104'), Decimal('0.122'), Decimal('0.077'), Decimal('0.122'), Decimal('0.077'), Decimal('0.153'), Decimal('0.239'), Decimal('0.734'), Decimal('2.142'), Decimal('1.685'), Decimal('1.5930'), Decimal('1.5930'), Decimal('0.6400'), Decimal('0.1670'), Decimal('55.047'), 9, Decimal('10.317'), 94, 22, Decimal('153000000.00'), 682385, datetime.date(2030, 6, 30), Decimal('38250000.00'), Decimal('60946463.00'), Decimal('17000000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Raphinha', 'Barcelona', 107, 8026, 148, 2024, '4', 36, 2862, 18, 10, 114, 91, 4, 0, 16, Decimal('19.2660'), Decimal('13.5270'), Decimal('39.2826'), Decimal('13.6504'), Decimal('17.7794'), Decimal('0.566'), Decimal('0.606'), Decimal('0.503'), Decimal('0.559'), Decimal('0.314'), Decimal('0.425'), Decimal('3.585'), Decimal('2.862'), Decimal('1.665'), Decimal('0.9340'), Decimal('0.9000'), Decimal('0.7390'), Decimal('0.1580'), Decimal('52.933'), 28, Decimal('32.793'), 205, 28, Decimal('72000000.00'), 918043, datetime.date(2028, 6, 30), Decimal('4000000.00'), Decimal('3737154.00'), Decimal('2571429.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Robert Lewandowski', 'Barcelona', 108, 227, 148, 2024, '4', 34, 2716, 27, 2, 115, 18, 1, 0, 24, Decimal('29.4143'), Decimal('2.4753'), Decimal('29.2428'), Decimal('6.6594'), Decimal('26.4412'), Decimal('0.895'), Decimal('0.975'), Decimal('0.795'), Decimal('0.876'), Decimal('0.066'), Decimal('0.082'), Decimal('3.811'), Decimal('0.596'), Decimal('1.190'), Decimal('0.9180'), Decimal('0.9080'), Decimal('0.8080'), Decimal('0.2350'), Decimal('35.902'), 29, Decimal('31.890'), 133, 36, Decimal('8400000.00'), 583333, datetime.date(2026, 6, 30), Decimal('311111.00'), Decimal('285575.00'), Decimal('289655.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Ronald Araújo', 'Barcelona', 109, 8091, 148, 2024, '4', 12, 771, 1, 1, 4, 4, 2, 0, 1, Decimal('1.1664'), Decimal('0.4866'), Decimal('4.3866'), Decimal('3.8932'), Decimal('1.1664'), Decimal('0.117'), Decimal('0.136'), Decimal('0.117'), Decimal('0.136'), Decimal('0.117'), Decimal('0.057'), Decimal('0.467'), Decimal('0.467'), Decimal('0.967'), Decimal('0.8570'), Decimal('0.8570'), Decimal('2.0550'), Decimal('0.2500'), Decimal('8.280'), 2, Decimal('1.653'), 8, 25, Decimal('27000000.00'), 134726, datetime.date(2031, 6, 30), Decimal('27000000.00'), Decimal('23148148.00'), Decimal('13500000.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))
('Sergi Domínguez', 'Barcelona', 110, 12823, 148, 2024, '4', 3, 177, 0, 0, 0, 0, 1, 0, 0, Decimal('0.0000'), Decimal('0.0000'), Decimal('2.0779'), Decimal('2.0779'), Decimal('0.0000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('0.000'), Decimal('2.113'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('4.156'), 0, Decimal('0.000'), 0, 19, Decimal('2400000.00'), 5955, datetime.date(2029, 6, 30), Decimal('0.00'), Decimal('0.00'), Decimal('0.00'), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 3, 14, 1, 7, 44, 588484, tzinfo=datetime.timezone.utc))

In [46]:
import antigravity
import inspect
print(inspect.getsource(antigravity))

import webbrowser
import hashlib

webbrowser.open("https://xkcd.com/353/")

def geohash(latitude, longitude, datedow):
    '''Compute geohash() using the Munroe algorithm.

    >>> geohash(37.421542, -122.085589, b'2005-05-26-10458.68')
    37.857713 -122.544543

    '''
    # https://xkcd.com/426/
    h = hashlib.md5(datedow, usedforsecurity=False).hexdigest()
    p, q = [('%f' % float.fromhex('0.' + x)) for x in (h[:16], h[16:32])]
    print('%d%s %d%s' % (latitude, p[1:], longitude, q[1:]))